const assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {createCosmeticExecutor}=require('../src/browser-cosmetic-executor');
(async()=>{
 const wc=new EventEmitter();let loading=true,url='https://example.com/a',errors=0,calls=[];
 Object.assign(wc,{isDestroyed:()=>false,getURL:()=>url,isLoading:()=>loading,executeJavaScript:async text=>{calls.push(text);if(text==='bad')throw Error('failed');}});
 const run=createCosmeticExecutor(()=>errors++);
 for(let i=0;i<60;i++)await run(wc,'executeJavaScript',['script-'+i]);
 assert.equal(wc.listenerCount('did-stop-loading'),1);assert.equal(calls.length,0);
 loading=false;wc.emit('did-stop-loading');await new Promise(setImmediate);
 assert.equal(calls.length,60);assert.equal(wc.listenerCount('did-stop-loading'),0);
 await run(wc,'executeJavaScript',['bad']);assert.equal(errors,1);
 loading=true;await run(wc,'executeJavaScript',['old']);url='https://example.com/b';loading=false;wc.emit('did-stop-loading');await new Promise(setImmediate);
 assert(!calls.includes('old'));
 loading=true;await run(wc,'executeJavaScript',['paused'],()=>false);loading=false;wc.emit('did-stop-loading');await new Promise(setImmediate);
 assert(!calls.includes('paused'));
 const race=run(wc,'executeJavaScript',['navigation-race']);loading=true;await race;
 assert(!calls.includes('navigation-race'));assert.equal(wc.listenerCount('did-stop-loading'),1);
 url='https://example.com/c';loading=false;wc.emit('did-stop-loading');await new Promise(setImmediate);
 assert(!calls.includes('navigation-race'));
 wc.insertCSS=async()=>{throw Error('CSS failed');};
 await run(wc,'insertCSS',['.ad {display:none}']);assert.equal(errors,2);
 loading=true;await run(wc,'executeJavaScript',['duplicate']);await run(wc,'executeJavaScript',['duplicate']);
 loading=false;wc.emit('did-stop-loading');await new Promise(setImmediate);
 assert.equal(calls.filter(text=>text==='duplicate').length,1);
 loading=true;await run(wc,'executeJavaScript',['destroyed-page']);wc.emit('destroyed');
 assert.equal(wc.listenerCount('did-stop-loading'),0);
 loading=false;wc.emit('did-stop-loading');await new Promise(setImmediate);
 assert(!calls.includes('destroyed-page'));
 console.log('Görsel filtre: tek yükleme dinleyicisi, hata yakalama, gezinme ve site duraklatma geçti.');
})().catch(error=>{console.error(error);process.exit(1);});
