const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  // Sürüklenen File nesnesinden gerçek disk yolu (Electron 32+'da file.path kaldırıldı)
  getFilePath: (file) => {
    try { return webUtils.getPathForFile(file); } catch (_) { return file && file.path; }
  },
  selectVideo: () => ipcRenderer.invoke('dialog:openVideo'),
  selectFolders: () => ipcRenderer.invoke('dialog:openFolders'),
  scanMediaPaths: (paths) => ipcRenderer.invoke('paths:scanMedia', paths),
  listMediaFolder: (filePath) => ipcRenderer.invoke('media:listFolder', filePath),
  selectFile: (kind) => ipcRenderer.invoke('dialog:openFile', kind),
  selectFolder: () => ipcRenderer.invoke('dialog:openFolder'),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  listHistory: () => ipcRenderer.invoke('history:list'),
  removeHistory: (id) => ipcRenderer.invoke('history:remove', id),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  listWatchLibrary: () => ipcRenderer.invoke('library:list'),
  updateWatchItem: (item) => ipcRenderer.invoke('library:upsert', item),
  removeWatchItem: (key) => ipcRenderer.invoke('library:remove', key),
  searchWatchLibrary: (query) => ipcRenderer.invoke('library:search', query),
  listLearningAnnotations: (mediaId) => ipcRenderer.invoke('library:annotations:list', mediaId),
  toggleLearningAnnotation: (annotation, saved) => ipcRenderer.invoke('library:annotations:toggle', { annotation, saved }),
  openLogFolder: () => ipcRenderer.invoke('logs:openFolder'),
  probeYoutube: (url, cookieBrowser) => ipcRenderer.invoke('media:probe', { url, cookieBrowser }),
  downloadYoutube: (opts) => ipcRenderer.invoke('media:download', opts),
  downloadYoutubeSubs: (opts) => ipcRenderer.invoke('media:downloadSubs', opts),
  findSiblingSubs: (videoPath) => ipcRenderer.invoke('media:findSiblingSubs', videoPath),
  cancelYoutubeDownload: () => ipcRenderer.invoke('media:cancelDownload'),
  readSubtitle: (p) => ipcRenderer.invoke('media:readSubtitle', p),
  writeSubtitle: (path, text, change) => ipcRenderer.invoke('media:writeSubtitle', { path, text, change }),
  saveSubtitleCopy: (sourcePath, text) => ipcRenderer.invoke('media:saveSubtitleCopy', { sourcePath, text }),
  getWaveform: (path) => ipcRenderer.invoke('media:waveform', path),
  startWatchFolder: (dir, options) => ipcRenderer.invoke('watch:start', dir, options),
  stopWatchFolder: () => ipcRenderer.invoke('watch:stop'),
  onWatchFiles: (cb) => ipcRenderer.on('watch:newFiles', (_e, files) => cb(files)),
  onMediaEvent: (cb) => ipcRenderer.on('media:event', (_e, data) => cb(data)),
  showBrowser: (tabId, bounds) => ipcRenderer.invoke('browser:show', { tabId, bounds }),
  hideBrowser: () => ipcRenderer.invoke('browser:hide'),
  setBrowserOccluded: (occluded) => ipcRenderer.invoke('browser:setOccluded', !!occluded),
  setBrowserBounds: (tabId, bounds) => ipcRenderer.invoke('browser:setBounds', { tabId, bounds }),
  navigateBrowser: (tabId, url) => ipcRenderer.invoke('browser:navigate', { tabId, url }),
  browserCommand: (tabId, command, value) => ipcRenderer.invoke('browser:command', { tabId, command, value }),
  setBrowserCaptureEnabled: (tabId, enabled) => ipcRenderer.invoke('browser:capture:setEnabled', { tabId, enabled }),
  createBrowserTab: () => ipcRenderer.invoke('browser:tab:create'),
  activateBrowserTab: (tabId) => ipcRenderer.invoke('browser:tab:activate', tabId),
  closeBrowserTab: (tabId) => ipcRenderer.invoke('browser:tab:close', tabId),
  getBrowserState: () => ipcRenderer.invoke('browser:getState'),
  setBrowserSessionRestore: (enabled) => ipcRenderer.invoke('browser:session:setRestore', enabled),
  updateBrowserSessionTab: (tab) => ipcRenderer.invoke('browser:session:updateTab', tab),
  listBrowserPlaces: () => ipcRenderer.invoke('browser:places:list'),
  toggleBrowserBookmark: (entry) => ipcRenderer.invoke('browser:places:toggleBookmark', entry),
  removeBrowserPlace: (kind, url) => ipcRenderer.invoke('browser:places:remove', kind, url),
  clearBrowserHistory: () => ipcRenderer.invoke('browser:places:clearHistory'),
  clearBrowserSiteCookies: (url) => ipcRenderer.invoke('browser:cookies:clearSite', url),
  clearBrowserCookies: () => ipcRenderer.invoke('browser:cookies:clearAll'),
  resetBrowserSession: () => ipcRenderer.invoke('browser:session:reset'),
  setBrowserOverlay: (tabId, payload) => ipcRenderer.invoke('browser:setOverlay', { tabId, payload }),
  startBrowserManga: (tabId, payload) => ipcRenderer.invoke('browser:manga:start', { ...payload, tabId }),
  toggleBrowserManga: (tabId, visible) => ipcRenderer.invoke('browser:manga:toggle', { tabId, visible }),
  clearBrowserManga: (tabId) => ipcRenderer.invoke('browser:manga:clear', { tabId }),
  retrySelectedBrowserManga: (tabId) => ipcRenderer.invoke('browser:manga:retrySelected', { tabId }),
  retryFailedBrowserManga: (tabId) => ipcRenderer.invoke('browser:manga:retryFailed', { tabId }),
  exportBrowserManga: (tabId, format) => ipcRenderer.invoke('browser:manga:export', { tabId, format }),
  captureBrowserPage: (tabId) => ipcRenderer.invoke('browser:capturePage', { tabId }),
  startBrowserTranslation: (tabId, payload) => ipcRenderer.invoke('browser:translation:start', { ...payload, tabId }),
  getBrowserTranslationSnapshot: (tabId) => ipcRenderer.invoke('browser:translation:snapshot', { tabId }),
  stopBrowserTranslation: (tabId) => ipcRenderer.invoke('browser:translation:stop', { tabId }),
  completeBrowserTranslation: (tabId) => ipcRenderer.invoke('browser:translation:completeAll', { tabId }),
  startBrowserLiveAsr: (tabId, options) => ipcRenderer.invoke('browser:liveAsr:start', { ...options, tabId }),
  sendBrowserLiveAsrChunk: (tabId, payload) => ipcRenderer.invoke('browser:liveAsr:chunk', { ...payload, tabId }),
  stopBrowserLiveAsr: () => ipcRenderer.invoke('browser:liveAsr:stop'),
  openBrowserAdapterFolder: () => ipcRenderer.invoke('browser:adapters:openFolder'),
  exportBrowserSubtitle: (payload) => ipcRenderer.invoke('browser:subtitle:export', payload),
  exportBrowserClip: (payload) => ipcRenderer.invoke('browser:clip:export', payload),
  onBrowserEvent: (cb) => {
    const listener = (_event, payload) => cb(payload);
    ipcRenderer.on('browser:event', listener);
    return () => ipcRenderer.removeListener('browser:event', listener);
  },
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  notify: (title, body) => ipcRenderer.invoke('notify', { title, body }),
  showInFolder: (p) => ipcRenderer.invoke('shell:showInFolder', p),
  getPaths: () => ipcRenderer.invoke('app:getPaths'),
  getEnvInfo: () => ipcRenderer.invoke('app:getEnvInfo'),
  getModelStatus: () => ipcRenderer.invoke('models:status'),
  benchmarkModel: (options) => ipcRenderer.invoke('models:benchmark', options),
  cancelModelBenchmark: () => ipcRenderer.invoke('models:benchmark:cancel'),
  copyText: (text) => ipcRenderer.invoke('clipboard:write', text),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (s) => ipcRenderer.invoke('settings:save', s),
  loadQueueState: () => ipcRenderer.invoke('queue:load'),
  saveQueueState: (snapshot) => ipcRenderer.invoke('queue:save', snapshot),
  saveImage: (payload) => ipcRenderer.invoke('media:saveImage', payload),
  exportSettings: () => ipcRenderer.invoke('settings:export'),
  importSettings: () => ipcRenderer.invoke('settings:import'),
  startTranscribe: (opts) => ipcRenderer.invoke('transcribe:start', opts),
  cancelTranscribe: () => ipcRenderer.invoke('transcribe:cancel'),
  updateYtdlp: () => ipcRenderer.invoke('maintenance:updateYtdlp'),
  shiftSubs: (filePath, offsetSec) => ipcRenderer.invoke('subs:shift', filePath, offsetSec),
  probeTracks: (filePath) => ipcRenderer.invoke('media:probeTracks', filePath),
  extractSubtitleTrack: (filePath, track) => ipcRenderer.invoke('media:extractSubtitleTrack', { filePath, track }),
  burnInStart: (videoPath, subPath, recoveryId = '') => ipcRenderer.invoke('burnin:start', videoPath, subPath, recoveryId),
  burnInCancel: () => ipcRenderer.invoke('burnin:cancel'),
  getBurnInRecovery: () => ipcRenderer.invoke('burnin:recovery:get'),
  recoverBurnIn: (id) => ipcRenderer.invoke('burnin:recovery:recover', id),
  discardBurnInRecovery: (id) => ipcRenderer.invoke('burnin:recovery:discard', id),
  onEvent: (cb) => {
    const listener = (_event, payload) => cb(payload);
    ipcRenderer.on('transcribe:event', listener);
    return () => ipcRenderer.removeListener('transcribe:event', listener);
  },
  onBurnInEvent: (cb) => {
    const listener = (_event, payload) => cb(payload);
    ipcRenderer.on('burnin:event', listener);
    return () => ipcRenderer.removeListener('burnin:event', listener);
  },
});
